language: python
dist: trusty
sudo: false
cache:
  pip: true
env:
  - C7N_TEST_WORKERS=8

python:
  - "2.7"
  - "3.6"
install:
  - pip install coveralls tox
script:
  - TOXENV=`tools/dev/citoxenv.py` tox
after_success:
  - if [ "$TRAVIS_PYTHON_VERSION" == "2.7" ]; then coveralls; fi
