AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  RegistrationHandler:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: "omnissm-register"
      Handler: "main"
      Tags:
        App: OmniSSM
      Runtime: "go1.x"
      CodeUri: "main.zip"
      Role: arn:aws:iam::644160558196:role/CloudCustodianRole
      Environment:
        Variables:
          REGISTRATION_TABLE: !Ref RegistrationTable
      Events:
        RegisterInstance:
          Properties:
            Method: POST
            Path: /register
          Type: Api
        RegisterId:
          Properties:
            Method: PATCH
            Path: /register
          Type: Api
  RegistrationTable:
    Type: 'AWS::Serverless::SimpleTable'
    Properties:
      TableName: omnissm-registrations
      Tags:
        App: OmniSSM
      PrimaryKey:
        Name: id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

      
